test JKfile
visenze/visearch-sdk-javascript pull request #57
Opened 2023-07-03 07:41 UTC by Sisyphus25

2023-07-03 09:01 UTC, wkurniawan07 requested changes

2023-07-03 09:01 UTC, wkurniawan07 commented on Jenkinsfile
> +    nodejs('NodeJS14')
Should be `NodeJS16`

2023-07-03 09:01 UTC, wkurniawan07 commented on Jenkinsfile
> +          if (env.BRANCH_NAME == 'master') {
There's quite some unusual practice in this repo:
- Both `master` and `develop` co-existing.
- `master` as the release-able state, and yet at the same time the default branch.
  - If `master` acts like the `production` branch in many of our other repos, it shouldn't be the default branch.
  - If `master` is the default branch and we release on demand e.g. if version number is bumped, which is quite a common practice in open source projects, then there needs to be more check here than just the branch name.

2023-07-03 09:02 UTC, Sisyphus25 commented on Jenkinsfile
> +          if (env.BRANCH_NAME == 'master') {
Master should not be default, I will update it.

2023-07-03 13:33 UTC, wkurniawan07 commented on Jenkinsfile
> +          if (env.BRANCH_NAME == 'master') {
@Sisyphus25 with that being done, maybe we can use the opportunity to rename the branch? `production` or `stable` sounds better.

2023-07-04 09:22 UTC, Sisyphus25 commented on Jenkinsfile
> +          if (env.BRANCH_NAME == 'master') {
It's changed now.

2023-07-05 03:48 UTC, wkurniawan07 requested changes

2023-07-05 03:48 UTC, wkurniawan07 commented on Jenkinsfile
> +          if (env.BRANCH_NAME == 'production') {
Instead of using if block here, you can consider using `when` block for the stage itself

2023-07-05 03:48 UTC, wkurniawan07 commented on Jenkinsfile
> +                string(name: 'TARGET_COMMITISH', value: 'master'),
Should be `production`, or better yet, just use `env.BRANCH_NAME`

2023-07-06 06:48 UTC, wkurniawan07 approved these changes
LGTM

2023-07-06 07:07 UTC, merged